
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package project;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 28;
  public static final int EQUALS = 34;
  public static final int CASE = 39;
  public static final int LOWER = 33;
  public static final int MINUS = 27;
  public static final int SEMICOLON = 15;
  public static final int AND = 30;
  public static final int TYPE_STR = 7;
  public static final int RPAR = 18;
  public static final int OR = 31;
  public static final int COMMA = 16;
  public static final int DIV = 29;
  public static final int BEGIN = 24;
  public static final int DIFFERENT = 35;
  public static final int PLUS = 26;
  public static final int ASSIGN = 19;
  public static final int MAIN = 22;
  public static final int IF = 8;
  public static final int ARITHMETIC = 14;
  public static final int EOF = 0;
  public static final int RETURN = 36;
  public static final int KEYWORD = 12;
  public static final int error = 1;
  public static final int LITERAL_CHAR = 4;
  public static final int HIGHER = 32;
  public static final int BREAK = 11;
  public static final int TYPE_NUM = 5;
  public static final int SWITCH = 38;
  public static final int TYPE_CHAR = 6;
  public static final int PUTW = 20;
  public static final int COLON = 37;
  public static final int PUTS = 21;
  public static final int ELSE = 9;
  public static final int LITERAL_CONSTANT = 3;
  public static final int OPERADOR = 23;
  public static final int WHILE = 10;
  public static final int DEFAULT = 40;
  public static final int END = 25;
  public static final int LPAR = 17;
  public static final int LITERAL_NUM = 2;
  public static final int IDENTIFIER = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LITERAL_NUM",
  "LITERAL_CONSTANT",
  "LITERAL_CHAR",
  "TYPE_NUM",
  "TYPE_CHAR",
  "TYPE_STR",
  "IF",
  "ELSE",
  "WHILE",
  "BREAK",
  "KEYWORD",
  "IDENTIFIER",
  "ARITHMETIC",
  "SEMICOLON",
  "COMMA",
  "LPAR",
  "RPAR",
  "ASSIGN",
  "PUTW",
  "PUTS",
  "MAIN",
  "OPERADOR",
  "BEGIN",
  "END",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "AND",
  "OR",
  "HIGHER",
  "LOWER",
  "EQUALS",
  "DIFFERENT",
  "RETURN",
  "COLON",
  "SWITCH",
  "CASE",
  "DEFAULT"
  };
}

