package project;


import java.awt.Color;
import static java.awt.Color.BLACK;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java_cup.runtime.Symbol;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import project.semantic.SemanticStack;
import project.semantic.SymbolTable.SymbolTable;
import project.semantic.Writer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fer Alvarado
 */
public class View_C0 extends javax.swing.JFrame {
    //private static ArrayList<ArrayList<Symbol>> _TokensList = new ArrayList<ArrayList<Symbol>>();
    private static ArrayList<Symbol> _Tokens = new ArrayList<Symbol>();

    private static ArrayList<Symbol> _TokensList = new ArrayList<Symbol>();
    private static final String fileInputPath = "Entrada.txt";
    private static final String fileOutputPath = "Salida.txt";
    /**
     * Creates new form View_C0
     */
    public View_C0() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txbInput = new javax.swing.JTextArea();
        chkBox_ReadFile = new javax.swing.JCheckBox();
        btnAnalize = new javax.swing.JButton();
        Lexical_errors = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_tokens = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_Lexical_errors = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txbParser = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txbSemantic = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_line = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_column = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("C-0");
        setBackground(new java.awt.Color(255, 255, 255));

        txbInput.setColumns(20);
        txbInput.setRows(5);
        txbInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txbInputMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txbInput);

        chkBox_ReadFile.setText("Analizar desde archivo solamente");
        chkBox_ReadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBox_ReadFileActionPerformed(evt);
            }
        });

        btnAnalize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAnalize.setText("Analizar");
        btnAnalize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizeActionPerformed(evt);
            }
        });

        tbl_tokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Token", "Tipo", "Línea", "Posición línea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbl_tokens);

        Lexical_errors.addTab("Tokens", jScrollPane5);

        jTable_Lexical_errors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Token", "Tipo", "Línea", "Posición línea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Lexical_errors.setCellSelectionEnabled(true);
        jTable_Lexical_errors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cell_selecction(evt);
            }
        });
        jScrollPane6.setViewportView(jTable_Lexical_errors);

        Lexical_errors.addTab("Errores léxicos", jScrollPane6);

        txbParser.setColumns(20);
        txbParser.setRows(5);
        jScrollPane1.setViewportView(txbParser);

        Lexical_errors.addTab("Errores sintácticos", jScrollPane1);

        txbSemantic.setColumns(20);
        txbSemantic.setRows(5);
        jScrollPane3.setViewportView(txbSemantic);

        Lexical_errors.addTab("Errores semanticos", jScrollPane3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("C-0");

        jLabel2.setText("Linea:");

        lbl_line.setText("0");

        jLabel4.setText("Columna:");

        lbl_column.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lexical_errors, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(chkBox_ReadFile)
                        .addGap(73, 73, 73)
                        .addComponent(btnAnalize)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_line, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_column, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_line, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(lbl_column, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBox_ReadFile)
                    .addComponent(btnAnalize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lexical_errors, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");

        jMenu4.setText("Abrir desde...");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu4);

        jMenu5.setText("Guardar como...");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizeActionPerformed
        try {
            clearTableTokens();
            clearTableTokens(jTable_Lexical_errors);
            txbSemantic.setText("");
            File dir =new File(".");
            String filePath =dir.getCanonicalPath()+"/src/project/";
            String inPath = filePath+ fileInputPath;
            System.out.println(inPath);
            
            //En el caso de que el usuario ingrese el codigo, lo que se escriba se guardará en un archivo y a la hora de la compilación se leerá ese archivo.
            if(!chkBox_ReadFile.isSelected()){
                writeFile(inPath,txbInput.getText());

            }
            scanFile(inPath);
            completeTableTokens(_Tokens);
            String lexicalErrors =tokensToString(_TokensList);
            String result = tokensToString(_Tokens);
            
            completeTableTokens(_TokensList,jTable_Lexical_errors);
            writeFile((filePath+fileOutputPath),result);
            SymbolTable.getInstance().clearAll();
            SemanticStack.getInstance().clearStack();
            Writer.getInstance().getCode().clear();
            parse(inPath);
            _TokensList.clear();
            _Tokens.clear();

        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAnalizeActionPerformed
    void search(String textt) {
        if (textt == null) {
            return;
        }
        String aktStr = txbInput.getText();
        int Index = aktStr.indexOf(textt);
        if (Index == -1) {
            JOptionPane.showMessageDialog(null, "String not found", "Dialog", JOptionPane.INFORMATION_MESSAGE);
        } else {
            txbInput.requestFocus();
            
            txbInput.select(Index, Index + textt.length());
            System.out.println(Index);
        }
    }
    //Selecciona una celda e invoca un metodo para senalar el error dentro del area de texto
    private void cell_selecction(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cell_selecction
        // TODO add your handling code here:
        int roww= jTable_Lexical_errors.rowAtPoint(evt.getPoint());
        int coll= jTable_Lexical_errors.columnAtPoint(evt.getPoint());
            if (jTable_Lexical_errors.isCellSelected(roww, coll)){
                String linea=String.valueOf(jTable_Lexical_errors.getValueAt(roww, coll));
                search(linea);                
        }
    }//GEN-LAST:event_cell_selecction

    private void txbInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txbInputMouseClicked
        try {
            // TODO add your handling code here:
            int viewToModel= txbInput.viewToModel(evt.getPoint());
            lbl_column.setText(String.valueOf(txbInput.getCaretPosition()- txbInput.getLineStartOffset(txbInput.getLineOfOffset(viewToModel))));
            lbl_line.setText(String.valueOf(txbInput.getLineOfOffset(viewToModel)));
            
        } catch (BadLocationException ex) {
            Logger.getLogger(View_C0.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_txbInputMouseClicked

    private void chkBox_ReadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBox_ReadFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBox_ReadFileActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        clearTableTokens();
        clearTableTokens(jTable_Lexical_errors);
        FileNameExtensionFilter filtro= new FileNameExtensionFilter("Archivo de texto","doc","txt");
        String nombre,contenido;
        File dir =new File(".");
        JFileChooser archivo= new JFileChooser();
        archivo.setFileFilter(filtro);
        archivo.setDialogTitle("Abrir archivo...");
        int comparar=archivo.showOpenDialog(null);
        if (comparar==JFileChooser.APPROVE_OPTION){
            dir = archivo.getSelectedFile();
            nombre=dir.getName();
            
            try{
                FileInputStream f1= new FileInputStream(dir);
                InputStreamReader f2= new InputStreamReader(f1);
                BufferedReader linea=new BufferedReader(f2);
                contenido="";
                while (linea.ready()){
                    String linea_arch=linea.readLine();
                    contenido=contenido + linea_arch + "\n";
                }
                linea.close();
                txbInput.setText(contenido);
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        FileNameExtensionFilter filtro= new FileNameExtensionFilter("Archivo de texto","txt");
        JFileChooser archivo= new JFileChooser();
        archivo.setFileFilter(filtro);
        archivo.setDialogTitle("Guardar archivo...");
        int comparar=archivo.showSaveDialog(null);
        if (comparar==JFileChooser.APPROVE_OPTION){
            final Formatter crear;
            try{
                crear = new Formatter(archivo.getSelectedFile()+".txt");
                crear.format(txbInput.getText());
                crear.close();
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        Color color=JColorChooser.showDialog(jPanel1, "Elige un color", Color.BLACK);
        jPanel1.setBackground(color);
        btnAnalize.setBackground(color);
        chkBox_ReadFile.setBackground(color);
        if (color==BLACK){
           btnAnalize.setForeground(Color.WHITE);
           jLabel1.setForeground(Color.WHITE);
           chkBox_ReadFile.setForeground(Color.WHITE);
        }
        else{
            btnAnalize.setForeground(Color.BLACK);
            jLabel1.setForeground(Color.BLACK);
            chkBox_ReadFile.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_C0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_C0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_C0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_C0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        File dir =new File(".");
        String filePath =dir.getCanonicalPath()+"/src/project/";
        String lexerPath = filePath+"Lexer.flex";
        String parserPath = filePath+"Parser.cup";
        generateLexer(lexerPath);
        generateParser(parserPath);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_C0().setVisible(true);
                
            }
        });
        
    }
        
        // Generates .flex file
    //Función encargada de generar el archivo .flex
    private static void generateLexer(String pFilePath){
        File file = new File(pFilePath);
        jflex.Main.generate(file);
    }
     //Muestra los errores de que hay en el programa, es decir si la sintaxis es correcta.
    private  void showParserErrors(ArrayList<String> pExpectedTokens, ArrayList<String> pErrorsLine, ArrayList<String> pErrors){
        txbParser.setText("");
        for(int iError = 0; iError != pExpectedTokens.size(); iError++){
            txbParser.setText(txbParser.getText()+ pErrorsLine.get(iError));
            txbParser.setText(txbParser.getText()+ pExpectedTokens.get(iError)+"\n");
            txbParser.setText(txbParser.getText()+ "------------------------------------------------------------\n");
        }
        if (pExpectedTokens.size()==0){
            System.out.println(_TokensList.size() );
            
            if (_TokensList.size() == 0){
                txbParser.setText("Parseo completado sin errores");
            }else{                
                txbParser.setText("Existen erorres lexicos");
            }
            
        }
    }
    //Realiza el pareser, muestra los errores del parser y muestra los errores semanticos.
    private void parse(String pFileInputPath){
        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(pFileInputPath));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        AnalizadorSintactico p = new AnalizadorSintactico(new AnalizadorLexico(bf));
        try {
            p.parse();
            showParserErrors(p.getExpectedTokens(), p.getLineErrors(), p.getErrors());
            if (SymbolTable.getInstance().getErrors().size() != 0){
                for(int iError = 0; iError != SymbolTable.getInstance().getErrors().size(); iError++){
                    txbSemantic.setText(txbSemantic.getText()+SymbolTable.getInstance().getErrors().get(iError)+"\n");
                }
            }else{
                txbSemantic.setText("Compilación completada");
                Writer.getInstance().writeAll();
            }
        } catch (Exception ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //genera el .cup
    private static void generateParser(String pFilePath){
        String[] asintactico = {"-parser", "AnalizadorSintactico", pFilePath};
        try {
            java_cup.Main.main(asintactico);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        moverArch("AnalizadorSintactico.java");
        moverArch("sym.java");

    }
    
    //Función encargada de escribir un archivo.
    private static boolean writeFile(String pFilePath, String pText){
        PrintWriter writer = null;
        try {
            writer = new PrintWriter(pFilePath);
            writer.print(pText);
            writer.close();
            return true;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }
    
    public String convertFileToString(BufferedReader bf){
        String result= null;
        String res = null;
        try {
            while ((result = bf.readLine())!=null){
                if (res!=null){
                   res+= (result+"\n");
                }else{
                    res= (result+"\n");
                }
            }
            return res;
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            return "";
        }
    
    }    

//Realiza el análisis de lossimbolos del programa.
    private  void scanFile(String pFileInputPath){
        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(pFileInputPath));
            if(chkBox_ReadFile.isSelected()){
                txbInput.setText(convertFileToString(new BufferedReader(new FileReader(pFileInputPath))));
            }
            AnalizadorLexico a = new AnalizadorLexico(bf);
            Symbol token = null;
            boolean isEOF = false;
            
            do {
                token = a.next_token();
                if(token.right != -1|| token.left != -1){
                    
                    System.out.println("--------token---------");
                    System.out.println("Simbolo: "+(sym.terminalNames[token.sym])+ " ,numero:" +token.sym);
                    System.out.println("Linea: "+token.left);
                    System.out.println("Columna: "+token.right);
                    //System.out.println("Value: "+token.value.toString());                    
                    System.out.println("--------token---------");
                    _Tokens.add(token);

                    if (TOKENS.get(token.sym).equals("ERROR")){
                        System.out.println("aca va un error "+token.value.toString());
                        _TokensList.add(token);
                    }
                    //insertToken(token);
                }else{
                    isEOF = true;
                }
            } while (!isEOF);            
            bf.close();
        } catch (Exception ex) {
            //Logger.getLogger(jflex.Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /*
    private static void insertToken(Symbol pToken){
        if (pToken != null){
            
            for(int i = 0; i < _TokensList.size(); i++){
                Symbol tempToken = _TokensList.get(i).get(0);         
                if (pToken.sym == tempToken.sym && pToken.value.toString().equals(tempToken.value.toString())){
                    _TokensList.get(i).add(pToken);
                    return;
                }
            }
            
            _TokensList.add(new ArrayList<Symbol>());
            _TokensList.get(_TokensList.size()-1).add(pToken);
            
        }
    }
    
    private static String tokensToString(){
        String result = "Token\tTipo\tLineas \n";
        for(int iRow = 0; iRow < _TokensList.size(); iRow++){
            result += _TokensList.get(iRow).get(0).value.toString() + "\t";
            result += TOKENS.get(_TokensList.get(iRow).get(0).sym) + "\t";
            // Se averigua la cantidad que hay en esa misma
            ArrayList<Integer> linesList = new ArrayList<Integer>();
            String lines = "";
            for(int iToken = 0; iToken < _TokensList.get(iRow).size(); iToken++){
                linesList.add(_TokensList.get(iRow).get(iToken).left);
            }
            int ocurrences = 0;
            while (linesList.size() !=0 ){
                ocurrences = Collections.frequency(linesList, linesList.get(0));
                if (ocurrences != 1){
                    lines += linesList.get(0) + "(" +ocurrences+ "), ";
                }else{
                    lines += linesList.get(0) + ", ";
                }
                ocurrences = 0;
                linesList.removeAll(Collections.singleton(linesList.get(0)));
            }
            result += lines;
            result += "\n";
            
        }
        return result;
    }
    */
    
    //Completa la tabla donde se muestran los tokens del programa, es la primer tabla de la interfaz.
    private void completeTableTokens(ArrayList<Symbol> pList){
        for(int iRow = 0; iRow < pList.size(); iRow++){
            tbl_tokens.setValueAt(pList.get(iRow).value.toString(), iRow, 0);
            tbl_tokens.setValueAt(sym.terminalNames[(pList.get(iRow).sym)], iRow, 1);
            tbl_tokens.setValueAt((pList.get(iRow)).left, iRow, 2);
            tbl_tokens.setValueAt((pList.get(iRow)).right, iRow, 3);
        }
    }
    //Setea la tabla de tokens.
    private void clearTableTokens(){
        for(int iRow = 0; iRow < tbl_tokens.getRowCount(); iRow++){
            tbl_tokens.setValueAt(null, iRow, 0);
            tbl_tokens.setValueAt(null, iRow, 1);
            tbl_tokens.setValueAt(null, iRow, 2);
            tbl_tokens.setValueAt(null, iRow, 3);
        }
    }
    
        //Completa la tabla donde se muestran los tokens del programa, es la primer tabla de la interfaz.
    private void completeTableTokens(ArrayList<Symbol> pList,JTable pTable){
        for(int iRow = 0; iRow < pList.size(); iRow++){
            pTable.setValueAt(pList.get(iRow).value.toString(), iRow, 0);
            pTable.setValueAt(sym.terminalNames[(pList.get(iRow).sym)], iRow, 1);
            pTable.setValueAt((pList.get(iRow)).left, iRow, 2);
            pTable.setValueAt((pList.get(iRow)).right, iRow, 3);
        }
    }
    //Setea la tabla de tokens.
   //Setea la tabla de tokens.
    private void clearTableTokens(JTable pTable){
        for(int iRow = 0; iRow < tbl_tokens.getRowCount(); iRow++){
            pTable.setValueAt(null, iRow, 0);
            pTable.setValueAt(null, iRow, 1);
            pTable.setValueAt(null, iRow, 2);
            pTable.setValueAt(null, iRow, 3);
        }
    }
    
    //Convierte cada tken en un string, mostrando la línea, columna, el token y el tipo de token.
    private static String tokensToString(ArrayList<Symbol> pList){
        String result = "Token                    \tTipo                     \tLineas \n\n";
        for(int iRow = 0; iRow < pList.size(); iRow++){
            result += pList.get(iRow).value.toString() + "\t\t\t\t\t";
            result += sym.terminalNames[(pList.get(iRow).sym)] + "\t\t\t";
            result += pList.get(iRow).left;
            result += "\n";
 
        }
        return result;
        
    }
    
    //Mueve un archio de una carpeta a otra.
    public static boolean moverArch(String archNombre) {
        boolean efectuado = false;
        File arch = new File(archNombre);
        if (arch.exists()) {
            //System.out.println("\n*** Moviendo " + arch + " \n***");
            Path currentRelativePath = Paths.get("");
            String nuevoDir = currentRelativePath.toAbsolutePath().toString()
                    + File.separator + "src" + File.separator
                    + "project" + File.separator + arch.getName();
            File archViejo = new File(nuevoDir);
            archViejo.delete();
            if (arch.renameTo(new File(nuevoDir))) {
                //System.out.println("\n*** Generado " + archNombre + "***\n");
                efectuado = true;
            } else {
                //System.out.println("\n*** No movido " + archNombre + " ***\n");
            }

        } else {
            //System.out.println("\n*** Codigo no existente ***\n");
        }
        return efectuado;
    }
    public static final ArrayList<String> TOKENS= new ArrayList<String>(
            Arrays.asList("EOF","ERROR","LITERAL","LITERAL","LITERAL","LITERAL",
            "PALABRAS_RESERVADAS","PALABRAS_RESERVADAS","PALABRAS_RESERVADAS","PALABRAS_RESERVADAS","PALABRAS_RESERVADAS",
            "PALABRAS_RESERVADAS","PALABRAS_RESERVADAS","PALABRAS_RESERVADAS","PALABRAS_RESERVADAS","PALABRAS_RESERVADAS",
            "PALABRAS_RESERVADAS","PALABRAS_RESERVADAS","PALABRAS_RESERVADAS","PALABRAS_RESERVADAS","PALABRAS_RESERVADAS",
            "PALABRAS_RESERVADAS","PALABRAS_RESERVADAS","PALABRAS_RESERVADAS","PALABRAS_RESERVADAS",
            "IDENTIFICADOR",
            "OPERADOR","OPERADOR","OPERADOR","OPERADOR","OPERADOR","OPERADOR",
            "OPERADOR","OPERADOR","OPERADOR","OPERADOR","OPERADOR","OPERADOR",
            "OPERADOR","OPERADOR", "OPERADOR","OPERADOR" 
            ));
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Lexical_errors;
    private javax.swing.JButton btnAnalize;
    private javax.swing.JCheckBox chkBox_ReadFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable_Lexical_errors;
    private javax.swing.JLabel lbl_column;
    private javax.swing.JLabel lbl_line;
    private javax.swing.JTable tbl_tokens;
    private javax.swing.JTextArea txbInput;
    private javax.swing.JTextArea txbParser;
    private javax.swing.JTextArea txbSemantic;
    // End of variables declaration//GEN-END:variables
}
